FROM gentoo/stage3:latest

# Sync repositories and install testing tools
RUN emerge-webrsync && \
    emerge -v --oneshot portage && \
    emerge -v dev-util/pkgdev dev-util/pkgcheck && \
    mkdir -p /etc/portage/env /etc/portage/repos.conf && \
    rm -rf /var/db/repos/gentoo

# Set working directory
WORKDIR /var/db/repos/cosmic-overlay
