#!/sbin/openrc-run
# Copyright 2026 Erik Dannenberg
# Distributed under the terms of the GNU General Public License v2

description="COSMIC greeter daemon, provides per-user config data to the greeter"

command="/usr/bin/cosmic-greeter-daemon"
command_background="true"
pidfile="${pidfile:-/run/${RC_SVCNAME}.pid}"
LOGFILE="/var/log/${RC_SVCNAME}.log"
start_stop_daemon_args="--stderr ${LOGFILE} --stdout ${LOGFILE}"

depend() {
	need dbus
	before display-manager
}
